name: CICD workflow using Docker
on: 
  push:
jobs:
  CICDJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'
          cache: maven
      - name: Build with Maven
        run:  mvn package
